name: Windows Iperius Remote

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download & Install FreeRDP
        run: powershell.exe -ExecutionPolicy Bypass -File install_freerdp.ps1

      - name: Verify FreeRDP Installation
        run: C:\FreeRDP\wfreerdp.exe /version
